name: Unit Tests

on:
  pull_request:
    # Only run workflow if a file in these paths is modified
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'extras/test/**'
      - 'src/**'

  push:
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'extras/test/**'
      - 'src/**'

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    env:
      BUILD_PATH: ${{ github.workspace }}/extras/test/build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install valgrind
        run: sudo apt-get --assume-yes install valgrind

      - name: Run unit tests
        run: |
          mkdir "$BUILD_PATH"
          cd "$BUILD_PATH"
          cmake ..
          make
          # Run tests and check for memory leaks
          valgrind --leak-check=yes --error-exitcode=1 bin/testNmeaParser

      - name: Install lcov
        run: sudo apt-get --assume-yes install lcov

      - name: Report code coverage
        run: |
          cd "$BUILD_PATH"
          lcov --directory . --capture --output-file coverage.info
          lcov --quiet --remove coverage.info '/usr/*' '*/extras/test/*' '*/src/lib/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ env.BUILD_PATH }}/coverage.info
          fail_ci_if_error: true
